### ISSUE TITLE
killall command in chat

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#1203]
I'm having a hard time getting the /killall command to work. 
I'm pretty sure @tyler3d can figure it out. what am I missing? 
Here's what I got: 

  killall: function (args) {
            if (this.playerTracker.userRole != UserRoleEnum.ADMIN && this.playerTracker.userRole != UserRoleEnum.MODER) { 
          this.writeLine("ERROR: access denied!");  
             return;
        }
          var count = 0;
        for (var i = 0; i < gameServer.clients.length; i++) {
       var playerTracker = gameServer.clients[i].playerTracker;
            while (playerTracker.cells.length > 0) {
                gameServer.removeNode(playerTracker.cells[0]);
                count++;
            }  
        }
    this.writeLine("You killed everyone KILLER!");
},

**Comment by ArixProject** [comment]
thanks)

**Comment by cowpits** [comment]
i keep crashing the server, i'm just missing something and i can't tell yet.

**Comment by ArixProject** [comment]
Ну попробуй исправить

**Comment by ArixProject** [comment]
Okay! Try to fix it

**Comment by Luka967** [comment]
What's crash error? @cowpits

**Comment by AlexHGaming** [comment]
@cowpits Try this: (Worked for me)

```javascript
         killall: function (args) {
        var count = 0;
        if (this.playerTracker.userRole != UserRoleEnum.ADMIN && this.playerTracker.userRole != UserRoleEnum.MODER) {
this.writeLine("ERROR: access denied!");
return;
}
        for (var i = 0; i < this.gameServer.clients.length; i++) {
            var playerTracker = this.gameServer.clients[i].playerTracker;
            while (playerTracker.cells.length > 0) {
                this.gameServer.removeNode(playerTracker.cells[0]);
                count++;
            }
        }
        this.writeLine("Removed " + count + " cells");
    },```

**Comment by AlexHGaming** [comment]
@cowpits gameServer on itself was undefined.

**Comment by cowpits** [comment]
@Luka967 with the code I posted, here's the crash. Perhaps I should mention this on ver. 1.3.5 i'm not sure it makes a difference. 

    >[FATAL] ReferenceError: gameServer is not defined
    at PlayerCommand.playerCommands.killall (/home/cabox/workspace/MultiOgar-1.3.5/src/modules/PlayerCommand.js:114:29)
    at PlayerCommand.executeCommandLine (/home/cabox/workspace/MultiOgar-1.3.5/src/modules/PlayerCommand.js:27:27)
    at GameServer.onChatMessage (/home/cabox/workspace/MultiOgar-1.3.5/src/GameServer.js:593:35)
    at PacketHandler.message_onChat (/home/cabox/workspace/MultiOgar-1.3.5/src/PacketHandler.js:268:21)
    at PacketHandler.handleMessage (/home/cabox/workspace/MultiOgar-1.3.5/src/PacketHandler.js:35:29)
    at GameServer.onClientSocketMessage (/home/cabox/workspace/MultiOgar-1.3.5/src/GameServer.js:423:22)
    at WebSocket.onMessage (/home/cabox/workspace/MultiOgar-1.3.5/src/GameServer.js:338:14)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.onbinary (/home/cabox/workspace/MultiOgar-1.3.5/node_modules/ws/lib/WebSocket.js:848:10)
    at /home/cabox/workspace/MultiOgar-1.3.5/node_modules/ws/lib/Receiver.js:628:18

**Comment by cowpits** [comment]
@AlexHGaming , thanks for trying to help. but I tried what you posted and I get this. 

>[FATAL] ReferenceError: gameServer is not defined
    at PlayerCommand.playerCommands.killall (/home/cabox/workspace/MultiOgar-1.3.5/src/modules/PlayerCommand.js:115:29)
    at PlayerCommand.executeCommandLine (/home/cabox/workspace/MultiOgar-1.3.5/src/modules/PlayerCommand.js:27:27)
    at GameServer.onChatMessage (/home/cabox/workspace/MultiOgar-1.3.5/src/GameServer.js:593:35)
    at PacketHandler.message_onChat (/home/cabox/workspace/MultiOgar-1.3.5/src/PacketHandler.js:268:21)
    at PacketHandler.handleMessage (/home/cabox/workspace/MultiOgar-1.3.5/src/PacketHandler.js:35:29)
    at GameServer.onClientSocketMessage (/home/cabox/workspace/MultiOgar-1.3.5/src/GameServer.js:423:22)
    at WebSocket.onMessage (/home/cabox/workspace/MultiOgar-1.3.5/src/GameServer.js:338:14)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.onbinary (/home/cabox/workspace/MultiOgar-1.3.5/node_modules/ws/lib/WebSocket.js:848:10)
    at /home/cabox/workspace/MultiOgar-1.3.5/node_modules/ws/lib/Receiver.js:628:18

**Comment by gyeyoqu** [comment]
@cowpits Do not lie when you say you've been working hard, you do not even know what you're doing,
on the other hand, write your playerCommand here and I'll give it to you, but start doing it yourself

**Comment by cowpits** [comment]
@gyeyoqu looks like you're attacking me for whatever reason. 
1st . where did I say I'm working hard and who are you to accuse me of lying? 
2nd. learn to read what people write and I quote myself in case you missed it the 1st time: "I'm having a hard time getting the /killall command to work."
3rd. if you have nothing positive to add to my request for help, then don't spam this discussion. It has nothing to do with you and I'm not asking YOU for help.

**Comment by cowpits** [comment]
@Luka967 and @AlexHGaming 
thank you guys and Alex your little nugget of me not defining this.gameserver was the key. so thank you. 
I got it to work with this. 

  killall: function (args) {
            if (this.playerTracker.userRole != UserRoleEnum.ADMIN && this.playerTracker.userRole != UserRoleEnum.MODER && this.playerTracker.userRole != UserRoleEnum.DEV) { 
          this.writeLine("ERROR: access denied!");  
             return;
        }
          var count = 0;
       var cell = this.playerTracker.cells[0];
        for (var i = 0; i < this.gameServer.clients.length; i++) {
       var playerTracker = this.gameServer.clients[i].playerTracker;
            while (playerTracker.cells.length > 0) {
                this.gameServer.removeNode(playerTracker.cells[0]);
                count++;
            }  
        }
    this.writeLine("You killed everyone KILLER!");
},

I was missing this. here [ for (var i = 0; i < **this**.gameServer.clients.length; i++) {  ]
and here [ var playerTracker = **this**.gameServer.clients[i].playerTracker; ]
and here [ **this**.gameServer.removeNode(playerTracker.cells[0]); ]

**Comment by AlexHGaming** [comment]
No problem :) I tested it on an earlier version and it worked for me lol

**Comment by cowpits** [comment]
I was totally not seeing it. this. does mean something lol.

**Comment by AlexHGaming** [comment]
@cowpits Dm's.

**Comment by ZfsrGhS953** [comment]
@gyeyoqu Stop harassing him for no reason, that won't make people think that you're a better programmer than you actually are. I think that you should just leave this community and come back when your coding skills are good enough to contribute to the project.
