### ISSUE TITLE
nodejs v10 error 

### ISSUE THREAD

**Issue by agaraq** [Megabyte918/MultiOgar-Edited#1475]
nodejs v10 error 

error message 

| [FATAL] RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 65535. Received -1566
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int16LE (internal/buffer.js:545:3)
    at Buffer.writeUInt16LE (internal/buffer.js:553:10)
    at BinaryWriter.writeUInt16 (/home/ubuntu/src/src/packet/BinaryWriter.js:10:395)
    at UpdateNodes.writeUpdateItems4 (/home/ubuntu/src/src/packet/UpdateNodes.js:5:25)
    at UpdateNodes.build (/home/ubuntu/src/src/packet/UpdateNodes.js:2:212)
    at PacketHandler.sendPacket (/home/ubuntu/src/src/PacketHandler.js:22:311)
    at PlayerTracker.sendUpdate (/home/ubuntu/src/src/PlayerTracker.js:18:317)
    at GameServer.updateClients (/home/ubuntu/src/src/GameServer.js:27:431)
    at GameServer.mainLoop (/home/ubuntu/src/src/GameServer.js:38:490)

**Comment by Petabyte918** [comment]
Use v8.11.4...

**Comment by WZ2100ModsFan** [comment]
@Petabyte918 Version of what exactly?

**Comment by Petabyte918** [comment]
Node

**Comment by Petabyte918** [comment]
v10 not stable for agar servers. use 8.x.x
