### ISSUE TITLE
console depends ? for mac

### ISSUE THREAD

**Issue by hamashexler** [Megabyte918/MultiOgar-Edited#1487]
# console depends

The console plus doesn't have depends I use mac it only has windows depends missing package.json idk what it needs however the console doesn't respond or anything its just a black screen idk if its cause the depends that are missing it doesn't respond.

MultiOgar-Edited/run

logs on chrome browser :-   
`(index):178 WebSocket connection to 'ws://127.0.0.1:1234/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ (index):178`
I fixed that but I still get many Error like it just crashes when I run it ect...
`(index):54 WebSocket is already in CLOSING or CLOSED state.`
`/Downloads/server/run/console-plus.js:189
      var hst = ws.upgradeReq.headers.host;
                              ^

TypeError: Cannot read property 'headers' of undefined
    at WebSocketServer.<anonymous> (/Users/HamaShexler/Downloads/server/run/console-plus.js:189:31)
    at emitTwo (events.js:126:13)
    at WebSocketServer.emit (events.js:214:7)
    at handleUpgrade (/Users/HamaShexler/Downloads/server/node_modules/ws/lib/websocket-server.js:89:16)
    at WebSocketServer.completeUpgrade (/Users/HamaShexler/Downloads/server/node_modules/ws/lib/websocket-server.js:282:5)
    at WebSocketServer.handleUpgrade (/Users/HamaShexler/Downloads/server/node_modules/ws/lib/websocket-server.js:221:10)
    at Server.WebSocketServer._ultron.on (/Users/HamaShexler/Downloads/server/node_modules/ws/lib/websocket-server.js:88:14)
    at emitThree (events.js:136:13)
    at Server.emit (events.js:217:7)
    at onParserExecuteCommon (_http_server.js:508:14)`

**Comment by Matthew-MK** [comment]
Use WS 2.3.1.

**Comment by hamashexler** [comment]
1 year passed

**Comment by B0RYS** [comment]
This project is only really meant to run on Linux and Windows.
