### ISSUE TITLE
Error when adding Bots

### ISSUE THREAD

**Issue by ElMay0r** [Megabyte918/MultiOgar-Edited#382]
when i put a number more than "0" on bots got this:

[FATAL] Error: Cannot find module 'vector2-node'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrador\Desktop\MultiOgar-Edited-maste
r\src\ai\BotPlayer.js:2:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by ElMay0r** [comment]
just had to isntall "vector2-node" 

solution: enter this on CMD "npm install vector2-node".
