### ISSUE TITLE
chat commands?

### ISSUE THREAD

**Issue by TrAnZiT21** [Megabyte918/MultiOgar-Edited#451]
i noticed that mgar has full chat commands and i wanted to know how to add chat commands for Admin like minion, killall, mass, kick, and ban. can anyone help me?

**Comment by AlexHGaming** [comment]
Isn't this client-sided?
Because vanilla doesn't support chat text?

**Comment by Luka967** [comment]
No, this is actually server-sided.
MultiOgar has player commands.
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/PlayerCommand.js

**Comment by TrAnZiT21** [comment]
I wanted to add /minion or something like that when i use /login command. So my server admins can control my server when i am gone or when i dont have access to the cmd.

**Comment by Luka967** [comment]
You'll need to add new player commands and add entries in [the user role list](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/enum/userRoles.json).
You need your admins' IP addresses for the user role list.

**Comment by TrAnZiT21** [comment]
i know that but when i try to add a command to the chat commands the server has alot of errors

**Comment by Osher12** [comment]
contact me on skype : pzaze11

**Comment by TrAnZiT21** [comment]
i got the command on the server but when i type it it chat this pops up in cmd
`>[FATAL] ReferenceError: id is not defined                                                                                                                                                              
    at PlayerCommand.playerCommands.minion (/home/cabox/workspace/ogar/src/modules/PlayerCommand.js:138:19)                                                                                             
    at PlayerCommand.executeCommandLine (/home/cabox/workspace/ogar/src/modules/PlayerCommand.js:46:27)                                                                                                 
    at GameServer.onChatMessage (/home/cabox/workspace/ogar/src/GameServer.js:464:35)                                                                                                                   
    at PacketHandler.message_onChat (/home/cabox/workspace/ogar/src/PacketHandler.js:202:21)                                                                                                            
    at PacketHandler.handleMessage (/home/cabox/workspace/ogar/src/PacketHandler.js:31:29)                                                                                                              
    at WebSocket.onMessage (/home/cabox/workspace/ogar/src/GameServer.js:281:26)                                                                                                                        
    at emitTwo (events.js:88:13)                                                                                                                                                                        
    at WebSocket.emit (events.js:173:7)                                                                                                                                                                 
    at Receiver.onbinary (/home/cabox/workspace/ogar/node_modules/ws/lib/WebSocket.js:848:10)                                                                                                           
    at /home/cabox/workspace/ogar/node_modules/ws/lib/Receiver.js:628:18  `

**Comment by TrAnZiT21** [comment]
can anyone help??

**Comment by Tyler3D** [comment]
http://pastebin.com/EszJbGZd

**Comment by Tyler3D** [comment]
Replace your playercommands.js with that

**Comment by Tyler3D** [comment]
I added minion, addbot, mass, spawnmass and a few other things

**Comment by TrAnZiT21** [comment]
woah it worked thx so much man!!! before i close this issue what is ur skype

**Comment by Tyler3D** [comment]
i don't have skype

**Comment by Tyler3D** [comment]
is discord good?

**Comment by TrAnZiT21** [comment]
yes

**Comment by Tyler3D** [comment]
https://discord.gg/Au5qr

**Comment by TrAnZiT21** [comment]
ok

**Comment by TrAnZiT21** [comment]
i have another issue i wanted to start

**Comment by TrAnZiT21** [comment]
on my site http://ftserver.tk the skins wont go on my players cell. do u know any way to fix that???

**Comment by Tyler3D** [comment]
idk about client stuff srry

**Comment by TrAnZiT21** [comment]
ok thx for the commands ima close this issue

**Comment by Megabyte918** [comment]
@Tyler3D That's great, you should make a pull request!

**Comment by Tyler3D** [comment]
@Megabyte918 Ok. But, first is it possible to input multiple values into chat commands? I was thinking of adding a few before I make a Pull request
