### ISSUE TITLE
[FATAL] TypeError: Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by matthewaptaylor** [Megabyte918/MultiOgar-Edited#471]
Whenever I connect to my server, the console quits and shows this error:
```
[FATAL] TypeError: Cannot read property 'destroy' of null
    at WebSocket.onClose (/home/pi/Teams/src/GameServer.js:288:23)
    at emitTwo (events.js:111:20)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.emitClose (/home/pi/Teams/node_modules/ws/lib/WebSocket.js:224:10)
    at _receiver.cleanup (/home/pi/Teams/node_modules/ws/lib/WebSocket.js:210:41)
    at Receiver.cleanup (/home/pi/Teams/node_modules/ws/lib/Receiver.js:500:15)
    at WebSocket.finalize (/home/pi/Teams/node_modules/ws/lib/WebSocket.js:210:22)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```
Can anyone help?

**Comment by Luka967** [comment]
Do you use the `uws` module? I've encountered this bug some time ago too but can't remember why.

**Comment by AlexHGaming** [comment]
What are you using to host your server?
If it's Codeanywhere you have to get into src files by typing in `cd src` `npm install`
If it's a solo server just do a redownload.

**Comment by AlexHGaming** [comment]
Did you mess with something with the gameserver.js?

**Comment by Megabyte918** [comment]
This does not happen with me (using the latest version of Update branch)

**Comment by cowpits** [comment]
I've had a few people ask me about that with the latest branch. I ended up giving them 1.4.2 with the fixes. Without the leaderboard name highlight fix. I'm going to destroy my container and do one or two to see if I get the same thing.

**Comment by cowpits** [comment]
ok i got the same thing on codeanywhere: 

Last login: Tue Jan 31 08:02:28 2017 from 54.69.152.243                                                                                                                        
cabox@box-codeanywhere:~/workspace$ cd multiogar-1.5.0-new                                                                                                                     
cabox@box-codeanywhere:~/workspace/multiogar-1.5.0-new$ npm install                                                                                                            
MultiOgar-Edited@1.5.0 /home/cabox/workspace/multiogar-1.5.0-new                                                                                                               
+-- vector2-node@0.0.3                                                                                                                                                         
`-- ws@2.0.0                                                                                                                                                                   
  `-- ultron@1.1.0                                                                                                                                                             
                                                                                                                                                                               
cabox@box-codeanywhere:~/workspace/multiogar-1.5.0-new$ cd run                                                                                                                 
cabox@box-codeanywhere:~/workspace/multiogar-1.5.0-new/run$ sh lin-Start.sh                                                                                                    
/usr/bin/nodejs                                                                                                                                                                
                                                                                                                                                                               
/home/cabox/workspace/multiogar-1.5.0-new/node_modules/ws/index.js:9                                                                                                           
const WebSocket = require('./lib/WebSocket');                                                                                                                                  
^^^^^                                                                                                                                                                          
SyntaxError: Use of const in strict mode.                                                                                                                                      
    at Module._compile (module.js:439:25)                                                                                                                                      
    at Object.Module._extensions..js (module.js:474:10)                                                                                                                        
    at Module.load (module.js:356:32)                                                                                                                                          
    at Function.Module._load (module.js:312:12)                                                                                                                                
    at Module.require (module.js:364:17)                                                                                                                                       
    at require (module.js:380:17)                                                                                                                                              
    at Object.<anonymous> (/home/cabox/workspace/multiogar-1.5.0-new/src/GameServer.js:2:17)                                                                                   
    at Module._compile (module.js:456:26)                                                                                                                                      
    at Object.Module._extensions..js (module.js:474:10)                                                                                                                        
    at Module.load (module.js:356:32)                                                                                                                                          
cabox@box-codeanywhere:~/workspace/multiogar-1.5.0-new/run$

**Comment by cowpits** [comment]
I don't get that issue on my windows box though. i can run the pre-updated branch version 1.5.0 with just the pakcethandler, chatmessage and updateladerboard js files fixes.

**Comment by Luka967** [comment]
I've just recently got the same error.
I'm thinking that it's due to near to instant connect and disconnect.
Client creation is very expensive and slow in MultiOgar.
Will investigate as soon as I come home. And probably switch to using `uws` because it's a native C++ addon.

**Comment by cowpits** [comment]
I'm sorry to be spamming this thread. I just noticed that on a windows server it works until the client refreshes. I uploaded a quick repro for windows:  https://youtu.be/60OdBxQ9jOA
On Ubuntu/Codeanywhere it's right when you start the server.

**Comment by Luka967** [comment]
No worries for thread spam, it's logs at the most, we accept them.

**Comment by Luka967** [comment]
![image](https://cloud.githubusercontent.com/assets/15956695/22477153/45f346c0-e7e5-11e6-8256-98c672ccbdaa.png)
The times really add up.
Several connections a second can really hurt the server.

**Comment by Luka967** [comment]
In the meantime there's a simple workaround for this problem; replace the line 288 of `GameServer.js` with this:
```js
if (ws._socket && ws._socket.destroy != null && typeof ws._socket.destroy == 'function') {
```

**Comment by Megabyte918** [comment]
It could be an issue with `ws` module itself, this never happened before or on any branches up until now. I'm guessing that since the server installs the latest `ws` module automatically, maybe the latest one has a bug??

**Comment by leboloss18k** [comment]
how i can use an older version of ws

**Comment by ItzLevvie** [comment]
@leboloss18k https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by Megabyte918** [comment]
I will make it so it installs version `1.1.0` by default.
