### ISSUE TITLE
[FATAL][18:55:04] Error: reserved fields must be empty

### ISSUE THREAD

**Issue by SomeoneCares11** [Megabyte918/MultiOgar-Edited#553]
everytime i got crash with this reason :  

```
[FATAL][18:55:04] Error: reserved fields must be empty
    at Receiver.error (/home/agar/node_modules/ws/lib/Receiver.js:321:18)
    at Receiver.processPacket (/home/agar/node_modules/ws/lib/Receiver.js:203:12)
    at Receiver.add (/home/agar/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/home/agar/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
[DEBUG][18:55:04] process.exit(1)
```

**Comment by AlexHGaming** [comment]
You messed with the receiver.js file
So I recommend to do this:
`**1.** Delete your node_modules folder.`
`**2.** Reinstall modules by either:
Solo server = run Install_dependencies.bat
Public = do an npm install.
`**3** Server should work.`
If this doesn't work, at what point did this error happen? Did it happen on server launch or in the middle of a game?

**Comment by AlexHGaming** [comment]
Then go to the package.json and find `ws: latest" <- (whatever it's called, you should be able to find it)
Remove the 'latest' and put 1.1.0.
If you have any errors just let me know

**Comment by AlexHGaming** [comment]
Is it working?

**Comment by SomeoneCares11** [comment]
I tried that, its not working

the problem was from the network firewall ,, thanks to @JaraLowell

**Comment by SomeoneCares11** [comment]
@AlexHGaming in the middle of the game.
It was a firewall problem, thanks to @JaraLowell
