### ISSUE TITLE
Cannot start after changing server name

### ISSUE THREAD

**Issue by matthewaptaylor** [Megabyte918/MultiOgar-Edited#623]
I just changed the first server welcome message, and I get this when I try to start it with index.js:

```
module.js:472
    throw err;
    ^

Error: Cannot find module './modules/Vec2'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/Warzone/src/PlayerTracker.js:2:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by Luka967** [comment]
Update your server.

**Comment by matthewaptaylor** [comment]
That worked. Thanks!
