### ISSUE TITLE
Server is always crashing

### ISSUE THREAD

**Issue by korlight** [Megabyte918/MultiOgar-Edited#699]
Hi, my servers crashes every 10 minutes. I updated nodejs last version. But it still gives an error. Can you help me?

http://prnt.sc/eni8ng

> [FATAL][09:19:57] TypeError: Cannot read property '_quadNode' of null
    at QuadNode.remove (/root/6/src/modules/QuadNode.js:61:13)
    at GameServer.removeNode (/root/6/src/GameServer.js:413:19)
    at GameServer.mainLoop (/root/6/src/GameServer.js:604:22)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by Tyler3D** [comment]
@korlight Please follow the issue template. Without many details of what you were doing and such, nobody can help you.

**Comment by Tyler3D** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template

**Comment by AGarRiBiA** [comment]
same problem with me ... #687

**Comment by MastaCoder** [comment]
Duplicate #687
