### ISSUE TITLE
Error at Startup...[Welp]

### ISSUE THREAD

**Issue by Mr-BrockLee** [Megabyte918/MultiOgar-Edited#709]
Im getting this error at startup help pls
`/home/cabox/workspace/i/src/modules/CommandList.js:821                                                                                                     
        Logger.print("Average score: " + (scores.reduce((x, y) => x + y) / sco                                                                             
                                                               ^^                                                                                          
SyntaxError: Unexpected token =>                                                                                                                           
    at exports.runInThisContext (vm.js:73:16)                                                                                                              
    at Module._compile (module.js:443:25)                                                                                                                  
    at Object.Module._extensions..js (module.js:478:10)                                                                                                    
    at Module.load (module.js:355:32)                                                                                                                      
    at Function.Module._load (module.js:310:12)                                                                                                            
    at Module.require (module.js:365:17)                                                                                                                   
    at require (module.js:384:17)                                                                                                                          
    at Object.<anonymous> (/home/cabox/workspace/i/src/index.js:3:16)                                                                                      
    at Module._compile (module.js:460:26)                                                                                                                  
    at Object.Module._extensions..js (module.js:478:10)    `

**Comment by Mr-BrockLee** [comment]
https://gyazo.com/286078f8b1e701c64d6c8cfb82170a22

**Comment by AlexHGaming** [comment]
reinstall the server

**Comment by AlexHGaming** [comment]
Or just use the latest version of commandlist.js

**Comment by Mr-BrockLee** [comment]
i did, didnt work

**Comment by Luka967** [comment]
ES6 arrow function notation isn't supported in older versions of node.js. Either update its version or replace `(x, y) => x + y` with `function(x, y) { return x + y; }`.

**Comment by Mr-BrockLee** [comment]
Still not working

**Comment by MastaCoder** [comment]
Open terminal or CMD, type in node -v

**Comment by Mr-BrockLee** [comment]
v0.12.10

**Comment by MastaCoder** [comment]
That's outdated, update to v5 or higher.

**Comment by Mr-BrockLee** [comment]
Sorry, But I am using CodeAnywhere and I am not sure how to update it.  @MastaCoder

**Comment by MastaCoder** [comment]
http://stackoverflow.com/questions/8191459/how-do-i-update-node-js

**Comment by Mr-BrockLee** [comment]
@MastaCoder Thx so much, It was their problem now it is fixed.

**Comment by MastaCoder** [comment]
No problem. :3

**Comment by smky** [comment]
I recommend digitalocean @Mr-BrockLee
