### ISSUE TITLE
i have some problem 

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#722]
usr/bin/nodejs                                                                                                                                            
| [INFO] 0 IP ban records loaded.                                                                                                                          
| [ERROR] SyntaxError: Unexpected number                                                                                                                   
    at Object.parse (native)                                                                                                                               
    at GameServer.loadUserList (/home/cabox/workspace/multiogar/src/GameServer.js:1036:25)                                                                 
    at new GameServer (/home/cabox/workspace/multiogar/src/GameServer.js:154:10)                                                                           
    at Object.<anonymous> (/home/cabox/workspace/multiogar/src/index.js:36:18)                                                                             
    at Module._compile (module.js:399:26)                                                                                                                  
    at Object.Module._extensions..js (module.js:406:10)                                                                                                    
    at Module.load (module.js:345:32)                                                                                                                      
    at Function.Module._load (module.js:302:12)                                                                                                            
    at Function.Module.runMain (module.js:431:10)                                                                                                          
    at startup (node.js:141:18)                                                                                                                            
| [ERROR] Failed to load ../src/enum/userRoles.json: Unexpected number                                                                                     
| [INFO] 419 bad words loaded                                                                                                                              
| [INFO] MultiOgar-Edited 1.6.0 - An open source multi-protocol ogar server                                                                                
| [INFO] WebSocket: ws                                                                                                                                     
| [INFO] Started stats server on port 8888                                                                                                                 
| [INFO] Listening on port 8081                                                                                                                            
| [INFO] Current game mode is Free For All                                                                                                                 
  __  __       _ _   _  ___                        _____    _ _ _           _    _   __    ___                                                             
 |  \/  |_   _| | |_(_)/ _ \  __ _  __ _ _ __     | ____|__| (_) |_ ___  __| |  / | / /_  / _ \                                                            
 | |\/| | | | | | __| | | | |/ _` |/ _` | '__|____|  _| / _` | | __/ _ \/ _` |  | || '_ \| | | |                                                           
 | |  | | |_| | | |_| | |_| | (_| | (_| | | |_____| |__| (_| | | ||  __/ (_| |  | || (_) | |_| |                                                           
 |_|  |_|\__,_|_|\__|_|\___/ \__, |\__,_|_|       |_____\__,_|_|\__\___|\__,_|  |_(_)___(_)___/                                                            
                             |___/                                                                                                                         
>

**Comment by AlexHGaming** [comment]
I think you changed something on line 1036 which made a syntax error.
Look at gameserver.js in the github files and copy the same line to what you had changed.
Or copy and paste it from the start of the function to the end.

**Comment by MastaCoder** [comment]
^

**Comment by Tyler3D** [comment]
I seems the op misconfigured the userRole json
