### ISSUE TITLE
I have this error all times 

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#741]
```
[NONE ][00:38:45] DISCONNECTED 190.130.199.229:63357, code: 1006, reason: "undefined", name: ""
[FATAL][00:38:45] TypeError: Cannot read property 'playerTracker' of undefined
    at GameServer.updateClients (C:\Users\Administrator\Desktop\ogar\BT 1\src\GameServer.js:489:28)
    at GameServer.mainLoop (C:\Users\Administrator\Desktop\ogar\BT 1\src\GameServer.js:749:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[DEBUG][00:38:45] process.exit(1)


```

The error "**Cannot read property'playerTracker' of undefined** " it is always after of "**DISCONNECTED 190.130.199.229:63357, code: 1006, reason: "undefined", name:** """

How to fix ? please thanks

**Comment by MastaCoder** [comment]
Your code isn't matching up.. https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L489 is whats at that line, you're doesn't match. Try again on a stock version of M-ED.
