### ISSUE TITLE
Syntax Errors ;-;

### ISSUE THREAD

**Issue by TurboCheetah** [Megabyte918/MultiOgar-Edited#757]
root@19665:/home/turbo/files/server1/src# sudo node index.js

/home/turbo/files/server1/src/modules/CommandList.js:821
        Logger.print("Average score: " + (scores.reduce((x, y) => x + y) / sco
                                                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/turbo/files/server1/src/index.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
------------------------------------------------------------------------------

I followed the guide and get that. My node version is 6.9.1 and server version is ubuntu 14.04

**Comment by Luka967** [comment]
The ES5 arrow function breaks a good amount of older node versions.
Replace `(x, y) => x + y` with `function(x, y) { return x + y; }`.

**Comment by MastaCoder** [comment]
Or just update Node.js ;)

**Comment by FantasyIsBae** [comment]
The size of your font @TurboCheetah is cancer.

**Comment by AlexHGaming** [comment]
no response.

**Comment by AlexHGaming** [comment]
@TurboCheetah
